import "server-only";
import { cookies } from "next/headers";

import type { OperatorPlan } from "@gtmstack/payments";
import type { BrandIdentity } from "@gtmstack/ai";

/**
 * Operator session.
 *
 * Sprint 6 V1 uses a signed cookie. Sprint 6.5 swaps in real Supabase Auth
 * (`@supabase/ssr`) — the read/write functions stay the same; only the
 * implementation changes. All callers go through this module so the swap is
 * a single-file change.
 *
 * Cookie shape carries the operator's working state across onboarding +
 * dashboard. When real Supabase comes in, most of this moves to the
 * `operators` / `storefronts` tables and only `userId` stays in the cookie.
 */

const COOKIE_NAME = "gtm_operator";

export type OperatorSession = {
  userId: string;
  email: string;
  organizationId: string;
  /** Whether onboarding has been completed. */
  onboarded: boolean;
  /** Operator-chosen template family. */
  theme?: "wellness" | "clinical" | "community";
  /** Brand voice generated by Claude. */
  brandVoice?: BrandIdentity;
  /** Operator-chosen brand name (may be set before or after brand voice gen). */
  brandName?: string;
  /** Slug used for storefront URL (e.g. "prime-wellness"). */
  storefrontSlug?: string;
  /** Selected product slugs (from the catalog step). */
  productSlugs?: string[];
  /** Operator's SaaS plan. */
  plan?: OperatorPlan;
  /** Stripe Connect account id once onboarded. */
  stripeAccountId?: string;
};

export type EmptySession = { userId: null };

/** Read the operator session. Returns `{ userId: null }` if not signed in. */
export async function readOperatorSession(): Promise<OperatorSession | EmptySession> {
  const store = await cookies();
  const raw = store.get(COOKIE_NAME)?.value;
  if (!raw) return { userId: null };
  try {
    const decoded = JSON.parse(Buffer.from(raw, "base64").toString("utf8"));
    if (typeof decoded?.userId !== "string") return { userId: null };
    return decoded as OperatorSession;
  } catch {
    return { userId: null };
  }
}

/** Patch the operator session. Creates one with defaults if missing. */
export async function writeOperatorSession(patch: Partial<OperatorSession>): Promise<void> {
  const existing = await readOperatorSession();
  const base: OperatorSession =
    existing.userId === null
      ? {
          userId: patch.userId ?? newId("usr"),
          email: patch.email ?? "",
          organizationId: patch.organizationId ?? newId("org"),
          onboarded: false,
        }
      : existing;
  const merged: OperatorSession = { ...base, ...patch };
  const store = await cookies();
  store.set(
    COOKIE_NAME,
    Buffer.from(JSON.stringify(merged), "utf8").toString("base64"),
    {
      httpOnly: true,
      sameSite: "lax",
      secure: process.env.NODE_ENV === "production",
      path: "/",
      maxAge: 60 * 60 * 24 * 30,
    },
  );
}

/** Clear the session — sign out. */
export async function clearOperatorSession(): Promise<void> {
  const store = await cookies();
  store.delete(COOKIE_NAME);
}

/** Require a signed-in operator or signal redirect. */
export async function requireOperator(): Promise<OperatorSession> {
  const s = await readOperatorSession();
  if (s.userId === null) {
    const { redirect } = await import("next/navigation");
    redirect("/signup");
  }
  // After the null check we know s is OperatorSession, not EmptySession.
  return s as OperatorSession;
}

function newId(prefix: string): string {
  const bytes = new Uint8Array(8);
  if (typeof globalThis.crypto !== "undefined" && typeof globalThis.crypto.getRandomValues === "function") {
    globalThis.crypto.getRandomValues(bytes);
  } else {
    for (let i = 0; i < bytes.length; i++) bytes[i] = Math.floor(Math.random() * 256);
  }
  const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
  return `${prefix}_${hex}`;
}
